# ===============================================
# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project 
# provides latest automated GCC Cross Compiler & Native (ARM & ARM64) 
# build-scripts and precompiled standalone toolchains for Raspberry Pi.


# Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>


# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ===============================================


os: linux
dist: bionic
language: minimal
matrix:
  include:
  - name: "GCC-9.2.0 32-bit Buster Pi[0-1]"
    env: GCC_VERSION=9.2.0  RPIOS_TYPE=buster RPI_TYPE=0-1
    language: minimal
  - name: "GCC-9.2.0 32-bit Buster Pi[2-3]"
    env: GCC_VERSION=9.2.0  RPIOS_TYPE=buster RPI_TYPE=2-3
    language: minimal
  - name: "GCC-9.2.0 32-bit Buster Pi[3+]"
    env: GCC_VERSION=9.2.0  RPIOS_TYPE=buster RPI_TYPE=3+
    language: minimal
  - name: "GCC-9.2.0 32-bit Stretch Pi[0-1]"
    env: GCC_VERSION=9.2.0  RPIOS_TYPE=stretch RPI_TYPE=0-1
    language: minimal
  - name: "GCC-9.2.0 32-bit Stretch Pi[2-3]"
    env: GCC_VERSION=9.2.0  RPIOS_TYPE=stretch RPI_TYPE=2-3
    language: minimal
  - name: "GCC-9.2.0 32-bit Stretch Pi[3+]"
    env: GCC_VERSION=9.2.0  RPIOS_TYPE=stretch RPI_TYPE=3+
    language: minimal
  - name: "GCC-8.3.0 32-bit Buster Pi[0-1]"
    env: GCC_VERSION=8.3.0  RPIOS_TYPE=buster RPI_TYPE=0-1
    language: minimal
  - name: "GCC-8.3.0 32-bit Buster Pi[2-3]"
    env: GCC_VERSION=8.3.0  RPIOS_TYPE=buster RPI_TYPE=2-3
    language: minimal
  - name: "GCC-8.3.0 32-bit Buster Pi[3+]"
    env: GCC_VERSION=8.3.0  RPIOS_TYPE=buster RPI_TYPE=3+
    language: minimal
  - name: "GCC-8.3.0 32-bit Stretch Pi[0-1]"
    env: GCC_VERSION=8.3.0  RPIOS_TYPE=stretch RPI_TYPE=0-1
    language: minimal
  - name: "GCC-8.3.0 32-bit Stretch Pi[2-3]"
    env: GCC_VERSION=8.3.0  RPIOS_TYPE=stretch RPI_TYPE=2-3
    language: minimal
  - name: "GCC-8.3.0 32-bit Stretch Pi[3+]"
    env: GCC_VERSION=8.3.0  RPIOS_TYPE=stretch RPI_TYPE=3+
    language: minimal
  - name: "GCC-6.3.0 32-bit Stretch Pi[0-1]"
    env: GCC_VERSION=6.3.0  RPIOS_TYPE=stretch RPI_TYPE=0-1
    language: minimal
  - name: "GCC-6.3.0 32-bit Stretch Pi[2-3]"
    env: GCC_VERSION=6.3.0  RPIOS_TYPE=stretch RPI_TYPE=2-3
    language: minimal
  - name: "GCC-6.3.0 32-bit Stretch Pi[3+]"
    env: GCC_VERSION=6.3.0  RPIOS_TYPE=stretch RPI_TYPE=3+
    language: minimal
  - name: "GCC-9.2.0 64-bit"
    env: GCC_VERSION=9.2.0 RPI_TYPE=64
    language: minimal
  - name: "GCC-8.3.0 64-bit"
    env: GCC_VERSION=8.3.0 RPI_TYPE=64
    language: minimal
  - name: "GCC-6.3.0 64-bit"
    env: GCC_VERSION=6.3.0 RPI_TYPE=64
before_install:
- sudo apt-get update -q; 
  sudo apt-get install unzip wget dos2unix -y; 
  sudo apt-get install build-essential libssh2-1-dev openssl libcurl3 -y; 
  dos2unix build-scripts/RTBuilder_32b;
  chmod +x build-scripts/RTBuilder_32b; 
  dos2unix build-scripts/RTBuilder_64b; 
  chmod +x build-scripts/RTBuilder_64b; 
  dos2unix patches/curl_stfp_patcher;
  chmod +x patches/curl_stfp_patcher;
  dos2unix tools/SF_deployer;
  chmod +x tools/SF_deployer;
install:
- sudo apt-get -y install gcc g++ gperf flex texinfo gawk gfortran texinfo bison
  libncurses-dev autoconf automake ccache tar figlet;
script:
- function keep_alive() { while true; do echo -en "\a"; sleep 60; done }
- keep_alive &
- bash build-scripts/RTBuilder_32b -g $GCC_VERSION -r $RPI_TYPE -o $RPIOS_TYPE;
- bash build-scripts/RTBuilder_64b -g $GCC_VERSION;
after_success:
- bash patches/curl_stfp_patcher;
- bash tools/SF_deployer;
cache:
- ccache: true
branches:
  only:
  - master
env:
  global:
  - CURL_VERSION=7.68.0
  - secure: MI97Ig3BiKpwjGL1Bwl/b9UuZ7ZKnz/IviyZnmGXVUNsovciQZRPg0DttZsc6upEFyLi0q8qc8ZKsWQsLA/0FoDRMiDzfpmiz8oy7C1MugY0AfViQP9PLCoUhltVFwEoFZS0MGR7eKmCedg9SVFIWBNwcGi7K8xqvSZlO6Adv+nxUBYU7QPUkqVVjxKslavDIcRlqDUtQfySkZcmFa/JzarwdYyusC1DuL/RTt8tUbp6MChvBFMZV/d+V69G9TRMkY32xKrSJ3GvQ/cuqN5eSi88e8K3PJP9oDfvcMCr+xF+cP7ztXrEMFmuiGvHAJf5TzeAGlfdqaBAYrNZ+mUuL/d50c7LJvF3PMmLLA0MUBVmyggFGb1l/UA7TARgTkV3VblE9vPFu9mDaQyOMGccFJ+4xwcsAxgI3nXNdmESz0M/bMUR47aIl2bGj/qennZZ6qW8GRId8iuceOYo570KGHdCnWAKKr/75Eds7p8D8u1QUdEjKyYO9EBbkgCJPw4Se+v5fp4Qej7bfBWtFgyadlPzxv3qYoq2Hq5VkmKLbY7cnbM2h+hrNjr8dnjNUIMzbrVbqlX08xKQ0qaa6e83Plm0K2nJ9AGrzIYkFj7Sdw1/XfGMm7inAIGOaPMzhy1V+UaSK/OuW77HW7fEgZwdMVOjSESPCU6uY8t0Bj1GeOE=
  - secure: DwYnMsvCduimQQjyOnOj0qTwf2KtILQ+OhFrnKSgnds3fGFoJZp2lMFW6OKHlLkUuvZKDC3O+wxWeRJSU/JCjl/rHduH+10K7U2HhRKW4V876AJ61m+m6u/6v+6YEIB0RBJxKf8p4RdYtCP9Bfqrd46zvZWO8LNb4JzjgvQ1NngqcggTyIS+CVVop0Xz4fty9FHGN82FM5ZU2VwLyQNuOo5bo8Om3uWTXSKw4YfC0CFL2McUmxZaTtuz0653VJsqGAe7IfDYc7HiL4UKBX+K7yPcvpG6MG4ejpzC2Cxovo1BJ1HrWOpYIx5EpDwwRT9slEpuV1opHI3hLWg/dlXrtFn9QJQYyDcV2q6UXKeGSFjFInu1GeqWxD8fv/vm8OcfNgceW+++3AO0C/ZfRimhgLJYc/R4B6In95H8Sqtm1gFmlmtH3aIHIESLaXkhT1eQ8z5gpO9xtNBEqk0M7mZ3uN9ygYGLxMKdhQK4an+jHQQSnumRi3++mY7ST9Ekqq+YmIvGpB93wLyWnt545GkawAxHOrwcHeTLkBRbDDCOUgt4VO0+ng+Tc3u/f9oWZWp8fBMG+PjF1HyZMEU7S7dPWD6KqScbdo7a/zKdU8RZFigb1NMREOlV3v2ku4SO6V/zhegkUOGCWeH1u8F5ddTj74HytK+2qtFc8NUSbCIVtvs=